default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: miserBrandService_development

test:
  <<: *default
  database: miserBrandService_test


production:
  <<: *default
  database: miserBrandService_production
  username: miserBrandService
  password: <%= ENV['MISERBRANDSERVICE_DATABASE_PASSWORD'] %>
