default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: '127.0.0.1'
  username: postgres
  password: password


development:
  <<: *default
  database: chamberCard_development

test:
  <<: *default
  database: chamberCard_test

production:
  <<: *default
  database: chamberCard_production
  username: postgres
  password: 
