default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: miserBrandGood_development

test:
  <<: *default
  database: miserBrandGood_test


production:
  <<: *default
  database: miserBrandGood_production
  username: miserBrandGood
  password: <%= ENV['MISERBRANDGOOD_DATABASE_PASSWORD'] %>
